#!/usr/bin/env python3
"""
Busca imagem em banco de imagens (Pexels) para ilustrar seções do artigo.

Licença Pexels: uso livre, sem atribuição obrigatória (creditamos por boa prática).
Falha graciosa: sem chave ou sem resultado, retorna None — o artigo é gerado
mesmo assim (só sem aquela imagem inline).

Requer (opcional): PEXELS_API_KEY  (chave grátis em pexels.com/api)

Uso (import):
    from buscar_imagem import buscar
    info = buscar("whatsapp business phone", "/caminho/img-1.jpg")
    # info = {"path","credit","credit_url","alt","origem"} ou None
"""
import os, re, sys, json, urllib.request, urllib.parse

PEXELS = "https://api.pexels.com/v1/search"
# User-Agent normal: a Pexels (Cloudflare) bloqueia o UA padrão do urllib com 403.
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36"

PHOTO_TERMS = {
    "a", "an", "and", "at", "by", "de", "da", "das", "do", "dos", "e", "em",
    "for", "in", "inside", "of", "on", "the", "to", "with",
    "photograph", "photography", "photo", "documentary", "editorial", "candid",
    "lens", "lighting", "light", "natural", "shallow", "depth", "field", "f1",
    "f1.8", "f2", "mm", "85mm", "50mm", "35mm", "24mm", "realistic",
    "photorealistic", "style", "corporate", "wide", "angle", "bright",
    "morning", "afternoon", "sunlight", "window", "windows", "background",
    "visible",
}

PEOPLE_TERMS = {
    "advisor", "agent", "analyst", "client", "consultant", "couple", "customer",
    "director", "employee", "leader", "manager", "people", "person",
    "professional", "salesman", "saleswoman", "team", "worker",
    "assessor", "atendente", "casal", "cliente", "consultor", "consultora",
    "corretor", "corretora", "equipe", "gerente", "lider", "líder", "pessoa",
    "pessoas", "profissional", "vendedor", "vendedora",
}

CONTEXT_TERMS = ("brazil", "latin")


def termos_significativos(text, limit=6):
    words = re.findall(r"[A-Za-zÀ-ÿ0-9.]+", text or "")
    chosen = []
    for word in words:
        clean = word.strip("._-").lower()
        if not clean or clean in PHOTO_TERMS:
            continue
        if re.fullmatch(r"\d+mm|f\d+(?:\.\d+)?", clean):
            continue
        chosen.append(word.strip(".,;:"))
        if len(chosen) >= limit:
            break
    return " ".join(chosen).strip()


def query_pexels(query, alt=None):
    raw = (query or "").strip()
    if len(raw.split()) < 15:
        return raw
    return termos_significativos(raw, 6) or termos_significativos(alt or "", 6) or raw


def envolve_gente(query, alt=None):
    text = f"{query or ''} {alt or ''}".lower()
    words = set(re.findall(r"[a-zà-ÿ]+", text))
    return bool(words & PEOPLE_TERMS)


def queries_com_contexto(query, alt=None):
    base = query_pexels(query, alt)
    if not base:
        return []
    lower = base.lower()
    out = []
    for term in CONTEXT_TERMS:
        if term not in lower:
            out.append(f"{base} {term}")
    out.append(base)

    deduped = []
    seen = set()
    for item in out:
        key = item.lower()
        if key not in seen:
            seen.add(key)
            deduped.append(item)
    return deduped


def parece_ia(photo):
    text = " ".join(str(photo.get(key) or "") for key in ("photographer", "photographer_url", "alt")).lower()
    return any(term in text for term in (
        "ai generative",
        "ai-generated",
        "generated by ai",
        "generative ai",
        "ia generativa",
    ))


def score_photo(photo, wants_people):
    text = " ".join(str(photo.get(key) or "") for key in ("photographer", "photographer_url", "alt")).lower()
    score = 0
    if int(photo.get("width") or 0) >= 1200:
        score += 4
    if any(term in text for term in ("brazil", "brazilian", "brasil", "são paulo", "sao paulo", "latin", "latina", "latino")):
        score += 5
    if wants_people and any(term in text for term in ("people", "person", "team", "woman", "man", "couple", "client", "pessoas", "mulher", "homem", "casal", "equipe")):
        score += 3
    if wants_people and any(term in text for term in ("diverse", "diversity", "group", "multiracial", "multiethnic", "diverso", "diversa")):
        score += 4
    return score


def search_photos(key, query, orientation):
    qs = urllib.parse.urlencode({
        "query": query, "per_page": 3,
        "orientation": orientation, "size": "large",
    })
    req = urllib.request.Request(f"{PEXELS}?{qs}",
                                 headers={"Authorization": key, "User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.loads(r.read())
    return data.get("photos", [])


def buscar(query, out_path, orientation="landscape", alt=None):
    key = os.environ.get("PEXELS_API_KEY")
    if not key:
        return None
    candidates = queries_com_contexto(query, alt)
    pexels_query = candidates[-1] if candidates else query_pexels(query, alt)
    try:
        selected_query = pexels_query
        usable = []
        for candidate in candidates:
            try:
                photos = search_photos(key, candidate, orientation)
            except Exception as e:
                print(f"  aviso: busca de imagem falhou ({candidate}): {e}", file=sys.stderr)
                continue
            usable = [photo for photo in photos if not parece_ia(photo)]
            if usable:
                selected_query = candidate
                break
        if not usable:
            return None
        wants_people = envolve_gente(query, alt)
        ph = max(usable, key=lambda photo: score_photo(photo, wants_people))
        src = ph["src"].get("large2x") or ph["src"].get("large") or ph["src"]["original"]
        img_req = urllib.request.Request(src, headers={"User-Agent": UA})
        with urllib.request.urlopen(img_req, timeout=30) as r:
            open(out_path, "wb").write(r.read())
        return {
            "path": out_path,
            "credit": ph.get("photographer", ""),
            "credit_url": ph.get("photographer_url", ""),
            "alt": ph.get("alt") or alt or selected_query,
            "origem": "Pexels",
            "query": selected_query,
        }
    except Exception as e:
        print(f"  aviso: download de imagem falhou ({pexels_query}): {e}", file=sys.stderr)
        return None


def main():
    if len(sys.argv) < 3:
        print('Uso: python3 buscar_imagem.py "query" saida.jpg')
        return 1
    info = buscar(sys.argv[1], sys.argv[2])
    print(json.dumps(info, ensure_ascii=False) if info else "sem imagem (sem chave ou sem resultado)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
